version: '3'
  
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log
      - ./log/nginx/error.log:/var/log/nginx/error.log
    depends_on:
      - php
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      PGDATA: /data/postgres
    volumes:
        - ./database:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - app-network
    restart: unless-stopped
  composer:
    image: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
networks:
  app-network:
    driver: bridge